export default {
    FONT_SIZE_TERMS: 10,
    FONT_SIZE_EXTRA_SMALL: 12,
    FONT_SIZE_DEFAULT: 16,
    FONT_SIZE_SMALL: 14,
    FONT_SIZE_SMALL_15: 15,
    FONT_SIZE_MEDIUM: 17,
    FONT_SIZE_EXTRA_MEDIUM: 20,
    FONT_SIZE_LARGE: 22,
    FONT_SIZE_XL: 24,
    FONT_SIZE_LARGE28: 28,
    FONT_SIZE_EXTRA_LARGE:30,
    FONT_SIZE_SUPREME: 34,
 };