export const FontFamily={
   'Gilroy':{
       100:'Gilroy-UltraLight',
       200:'Gilroy-UltraLight',
       300:'Gilroy-UltraLight',
       400:'Gilroy-Regular',
       500:'Gilroy-SemiBold',
       600:'Gilroy-SemiBold',
       700:'Gilroy-Bold',
       800:'Gilroy-ExtraBold'
    },
    'ChakraPetch':{
        100:'ChakraPetch-Light',
        200:'ChakraPetch-Light',
        300:'ChakraPetch-Light',
        400:'ChakraPetch-Regular',
        500:'ChakraPetch-SemiBold',
        600:'ChakraPetch-SemiBold',
        700:'ChakraPetch-Bold',
        800:'ChakraPetch-Bold'
    }
}